import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from langchain_core.tools import tool
from typing import Optional
from dotenv import load_dotenv

from langchain_groq import ChatGroq
from backend.core.config import settings

load_dotenv()

@tool
def send_visit_summary_email(user_email: str, ai_summary: str, triage_label: str) -> bool:
    """
    Sends an automated visit summary email to the patient after every consultation.
    """
    sender_email = os.getenv("SENDER_EMAIL")
    app_password = os.getenv("GMAIL_APP_PASSWORD")

    if not sender_email or not app_password:
        print("Warning: SENDER_EMAIL or GMAIL_APP_PASSWORD is missing in .env. Cannot send summary email.")
        return False
        
    try:
        # Summarize the AI response for the email so it's not too big
        llm = ChatGroq(
            model=settings.GROQ_MODEL,
            temperature=0,
            api_key=settings.GROQ_API_KEY
        )
        brief_summary = llm.invoke(f"Summarize the following clinical advice into a single, very concise and encouraging 2-sentence paragraph. Do not use markdown. Advice: {ai_summary}").content

        # Determine color based on triage level for a dynamic design
        triage_lower = triage_label.lower()
        if "emergent" in triage_lower or "red" in triage_lower or "critical" in triage_lower:
            accent_color = "#e63946" # Red
        elif "urgent" in triage_lower or "yellow" in triage_lower:
            accent_color = "#f4a261" # Orange
        else:
            accent_color = "#2a9d8f" # Green

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
            body {{ font-family: 'Inter', sans-serif; background-color: #f7f9fc; margin: 0; padding: 20px; }}
            .container {{ max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.05); }}
            .header {{ background: #ffffff; border-bottom: 4px solid {accent_color}; color: #334155; padding: 30px 20px; text-align: center; }}
            .header h1 {{ margin: 0; font-size: 24px; font-weight: 700; }}
            .content {{ padding: 30px; color: #334155; }}
            .triage-badge {{ display: inline-block; background-color: {accent_color}22; color: {accent_color}; font-weight: 600; padding: 8px 16px; border-radius: 20px; font-size: 14px; margin-bottom: 20px; }}
            .advice-card {{ background: #f8fafc; border-left: 4px solid {accent_color}; padding: 20px; border-radius: 0 8px 8px 0; margin-bottom: 25px; line-height: 1.6; font-size: 15px; }}
            .footer {{ background: #f1f5f9; padding: 20px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; }}
            .footer p {{ margin: 5px 0; }}
        </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <img src="cid:nexacare_logo" alt="NexaCare Logo" style="max-height: 70px; display: block; margin: 0 auto;">
                </div>
                <div class="content">
                    <p style="font-size: 16px; margin-top: 0;">Hello,</p>
                    <p style="font-size: 16px; margin-bottom: 25px;">Thank you for using our AI triage system. Here is a brief overview of your consultation today.</p>
                    
                    <div class="triage-badge">
                        Triage Level: {triage_label}
                    </div>
                    
                    <div class="advice-card">
                        <strong>Key Takeaway:</strong><br/><br/>
                        {brief_summary}
                    </div>
                </div>
                <div class="footer">
                    <p>This is an automated summary generated by AI.</p>
                    <p><strong>Please remember to consult a real medical professional for emergencies.</strong></p>
                </div>
            </div>
        </body>
        </html>
        """
        
        # Create the email message
        msg = MIMEMultipart('related')
        msg['From'] = f"NexaCare <{sender_email}>"
        msg['To'] = user_email
        msg['Subject'] = "Your NexaCare Visit Summary"
        
        msg_alternative = MIMEMultipart('alternative')
        msg.attach(msg_alternative)
        msg_alternative.attach(MIMEText(html_content, 'html'))
        
        try:
            from email.mime.image import MIMEImage
            logo_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))), "frontend", "Icons", "LOGO.png")
            with open(logo_path, "rb") as img_file:
                image = MIMEImage(img_file.read(), name="LOGO.png")
                image.add_header('Content-ID', '<nexacare_logo>')
                image.add_header('Content-Disposition', 'inline', filename='LOGO.png')
                msg.attach(image)
        except Exception as e:
            print(f"Could not attach logo: {e}")
        
        # Connect to Gmail's SMTP server
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, app_password)
        server.send_message(msg)
        server.quit()
        
        return True
    except Exception as e:
        print(f"Failed to send summary email: {e}")
        return False

